### PR TITLE
sahar/footer

### PR DESCRIPTION
**Pull request by Sahar-Kavousi**
## Describe your changes

Worked on the footer layout for both mobile and desktop
added social media icons into the footer
Fixed te scrolling issue which was happening in all the pages 
worker on the responsiveness of all the NAV bar pages except Home page (Create profile, profile page and Home need styling)
Modified the breakpoints 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## What kind of feedback do you need?

need a quick look 

## Checklist:

- [x] I have performed a self-review of my code
- [ ] I have recommended where to start and how to proceed with the review
- [ ] I have done a git pull from DEV to ensure this PR is up to date

### CODE REVIEW

**Review by ktechgau — APPROVED** [review]

**Review by Lyndallh — DISMISSED** [review]
It looks like there is something weird going on with this PR. There are a lot of changes in the files that are not related to the footer. I think Shay will need check over it to make sure nothing gets written over accidentally.

**Comment by shayzimm** [comment]
I think you need to do a git pull from dev, Sahar. This feature branch isn't up to date, let me know if you need help :)

**Comment by Sahar-Kavousi** [comment]
> It looks like there is something weird going on with this PR. There are a lot of changes in the files that are not related to the footer. I think Shay will need check over it to make sure nothing gets written over accidentally.

The thing is that I was working on the footer, but I found out codes that were ovveriding each other and also effecting other pages layout. I had to fix all those errors on the pages to be able to implement the footer structure and style. I just restructured some areas, we won't loose any code.

**Comment by Sahar-Kavousi** [comment]
> I think you need to do a git pull from dev, Sahar. This feature branch isn't up to date, let me know if you need help :)

I did git pull from dev last night before pushing my code.

**Review by shayzimm — APPROVED** [review]
This looks great!!

**Pull request merged**
