### PR TITLE
Content Page with Help Form and Page

### PR DESCRIPTION
**Pull request by ktechgau**
## Describe your changes

Contact page with Contact form structured and responsive. Detailed styling to follow from Sahar our UI/UX extraordinaire!

**NOTE**
I have set the handleSubmission to be handled by Formspree for now until we add a backend API for contact forms. At the moment the email submission will go to my email. Testing to follow once live.

Screenshot 2024-03-27 at 1 53 08 pm

Screenshot 2024-03-27 at 1 53 50 pm

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## What kind of feedback do you need?

Quick Look

## Checklist:

- [x] I have performed a self-review of my code
- [x] I have recommended where to start and how to proceed with the review

### CODE REVIEW

**Comment by Lyndallh** [comment]
Hi Karla, looks great. Last night we spoke about this form also covering the MVP for 'report something inappropriate' by including the ability to select the message type. Sorry, I should have added it to the card, but I just kept it in my head because at that point I was going to be working on it.

**Comment by ktechgau** [comment]
> Hi Karla, last night we spoke about this form also covering the MVP for 'report something inappropriate' by including the ability to select the message type. Sorry, I should have added it to the card, but I just kept it in my head because at that point I was going to be working on it. 

Ah yes forgot a about that. So a drop down menu of some sort? Options something like General Enquiry/Report Abuse?

**Comment by ktechgau** [comment]
> Hi Karla, last night we spoke about this form also covering the MVP for 'report something inappropriate' by including the ability to select the message type. Sorry, I should have added it to the card, but I just kept it in my head because at that point I was going to be working on it. 

Ah yes forgot a about that. So a drop down menu of some sort? Options something like General/Report

**Comment by Sahar-Kavousi** [comment]
Excellent!

**Pull request closed without merging**
